# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_optimal_points <- function(moments, N) {
    .Call('_scmc_calc_optimal_points', PACKAGE = 'scmc', moments, N)
}

sample_optimal_points <- function(x, N) {
    .Call('_scmc_sample_optimal_points', PACKAGE = 'scmc', x, N)
}

