# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

divided_diffs <- function(xs, ys) {
    .Call('_scmc_divided_diffs', PACKAGE = 'scmc', xs, ys)
}

C_lagrange_weights <- function(col_pts, indices) {
    .Call('_scmc_C_lagrange_weights', PACKAGE = 'scmc', col_pts, indices)
}

lagrange_eval <- function(var_vecs, nodes, y, lambda_prods) {
    .Call('_scmc_lagrange_eval', PACKAGE = 'scmc', var_vecs, nodes, y, lambda_prods)
}

monom_eval <- function(x, coefs) {
    .Call('_scmc_monom_eval', PACKAGE = 'scmc', x, coefs)
}

newton_eval <- function(x, nodes, coefs) {
    .Call('_scmc_newton_eval', PACKAGE = 'scmc', x, nodes, coefs)
}

calc_optimal_points <- function(moments, N) {
    .Call('_scmc_calc_optimal_points', PACKAGE = 'scmc', moments, N)
}

sample_optimal_points <- function(x, N) {
    .Call('_scmc_sample_optimal_points', PACKAGE = 'scmc', x, N)
}

